"""initial

Revision ID: 0c5f83145a02
Revises: f5d46b663778
Create Date: 2024-08-03 17:48:30.690407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5f83145a02'
down_revision: Union[str, None] = 'f5d46b663778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('values', sa.String(), nullable=False))
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.drop_column('users', 'value')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.drop_column('users', 'values')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
